### ISSUE TITLE
Tested on flysky nirvana nv14

### ISSUE THREAD

**Issue by nightflasher** [ExpressLRS/ElrsTelemWidget#4]
I just wanna say THANK YOU for your work!
Attached is a picture from my NV14 screen, also with both sizes. Feel free to use! 
Firmware: edgeTX 2.7.1
I recommend your widget to our fpv-community.de forum, because it should be on everybody's radio. 
![screenshot_elrst_nv14](https://user-images.githubusercontent.com/3342605/186766258-d6bab2d0-bc76-4e23-b04b-617e672a214a.jpg)

**Comment by CapnBry** [comment]
Nice! I've pushed a change to not display the flight mode if it is "0" too, so that will be fixed in the next release too.
