### ISSUE TITLE
Not showing as expected

### ISSUE THREAD

**Issue by L1cardo** [ExpressLRS/ElrsTelemWidget#5]
Not showing batt and current item as shown in README file when it is a small wiget.

EdgeTX: 2.8
ELRS: 3.0.1

This is my radio.
![image](https://user-images.githubusercontent.com/33802186/205425739-44a34dd7-2316-466c-b593-3cc5633e87f7.jpeg)

This is what is in README.
![image](https://user-images.githubusercontent.com/33802186/205425899-5d608bbf-41d8-40ae-bc02-d68be3a13aa6.png)

Have you adjust the layout of the widget? Actually old style shows more info without going into full screen mod.

**Comment by CapnBry** [comment]
No, EdgeTX made the widgets 1 pixel smaller in 2.8 so it thinks it needs to be the smallest version to fit. I'll fix all the layouts this weekend, I was hoping to convince them that they should stay the same size but failed :'(

**Comment by L1cardo** [comment]
Ok, thanks mate. 
I am wondering if it will work just to change this line from 85 to 84?
https://github.com/ExpressLRS/ElrsTelemWidget/blob/b39aba0c3c27d7908a56573b68e4868fca02b2cd/src/WIDGETS/ELRST/main.lua#L213

**Comment by CapnBry** [comment]
Yeah that's what I was talking about. _Some_ of the layout dimensions are 1 pixel smaller in one dimension. It's a real good time to create telemetry screens with all the possible layouts and validate it resizes properly on both EdgeTX 2.7 and 2.8 but it is done. I was also worried some of the layouts would have overlapping elements now if I had packed them too close, but looks ok I think.

Should be resolved with v4 release.
